apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: production
spec:
  selector:
    matchLabels:
      app: sample-app
      environment: production
  template:
    metadata:
      labels:
        app: sample-app
        environment: production
    spec:
      containers:
        - name: sample-app
          image: artpasut/sample-app:1.0.2 # {"$imagepolicy": "flux-system:sample-app-image-policy"}
          restartPolicy: Always
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: dockercred
