apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sample-app-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sample-app-image-repo
  policy:
    semver:
      range: 1.x.x